### ISSUE TITLE
Normal or Uniform?

### ISSUE THREAD

**Issue by ArashPartow** [entangledloops/heuristicSearch#1]
In the wiki page, you have the following statement:

> The distribution of digits in prime numbers obeys a normal distribution.

Perhaps you meant to say: _uniform distribution_

**Comment by entangledloops** [comment]
Thanks! Uniform distribution is correct, not normal. I was getting ahead of myself&#8212;a normal distribution appears when the primes are multiplied together in random pairs and their semiprime products are tallied up.
